/**
 * Activity Type Definitions
 *
 * Comprehensive types for co-curricular activities submitted by students
 * and reviewed/approved by faculty. Tracks proof, status, and metadata.
 *
 * Requirements:
 * - Activity lifecycle (DRAFT → SUBMITTED → UNDER_REVIEW → APPROVED/REJECTED)
 * - Proof file uploads (Cloudinary CDN)
 * - Faculty remarks and feedback
 * - Activity categorization (SPORTS, TECH, CULTURAL, etc.)
 */

import type { User } from "./user.types";

/**
 * Activity categories for filtering and organization
 * @enum {string}
 */
export enum ActivityCategory {
  SPORTS = "sports",
  TECH = "tech",
  CULTURAL = "cultural",
  COMMUNITY_SERVICE = "community_service",
  ACADEMIC = "academic",
  LEADERSHIP = "leadership",
  ENTREPRENEURSHIP = "entrepreneurship",
  VOLUNTEER = "volunteer",
  RESEARCH = "research",
  ARTS_MUSIC = "arts_music",
}

/**
 * Specific activity types within each category
 * @enum {string}
 */
export enum ActivityType {
  // Sports
  SPORTS_COMPETITION = "sports_competition",
  SPORTS_TRAINING = "sports_training",

  // Tech
  HACKATHON = "hackathon",
  TECH_TALK = "tech_talk",
  CODING_WORKSHOP = "coding_workshop",
  TECH_PROJECT = "tech_project",

  // Cultural
  CULTURAL_EVENT = "cultural_event",
  CULTURAL_PERFORMANCE = "cultural_performance",

  // Community Service
  COMMUNITY_EVENT = "community_event",
  CHARITY_DRIVE = "charity_drive",
  MENTORING = "mentoring",

  // Academic
  PRESENTATION = "presentation",
  PAPER_PUBLICATION = "paper_publication",
  SEMINAR_ATTENDED = "seminar_attended",

  // Leadership
  CLUB_LEADERSHIP = "club_leadership",
  EVENT_ORGANIZING = "event_organizing",

  // Entrepreneurship
  STARTUP_LAUNCH = "startup_launch",
  BUSINESS_PITCH = "business_pitch",

  // Volunteer
  VOLUNTEER_WORK = "volunteer_work",

  // Research
  RESEARCH_PROJECT = "research_project",

  // Arts & Music
  MUSIC_PERFORMANCE = "music_performance",
  ART_EXHIBITION = "art_exhibition",
}

/**
 * Activity submission status lifecycle
 * @enum {string}
 */
export enum ActivityStatus {
  DRAFT = "draft",
  SUBMITTED = "submitted",
  UNDER_REVIEW = "under_review",
  APPROVED = "approved",
  REJECTED = "rejected",
  REVISION_REQUESTED = "revision_requested",
}

/**
 * Proof file metadata
 * Stores Cloudinary URLs and file information
 */
export interface ProofFile {
  /** Unique file ID (Cloudinary public_id) */
  id: string;

  /** Display name / original filename */
  name: string;

  /** File type (image, pdf, video, document) */
  type: "image" | "pdf" | "video" | "document";

  /** Cloudinary URL (optimized for display) */
  url: string;

  /** Cloudinary secure URL (HTTPS) */
  secureUrl: string;

  /** File size in bytes */
  size: number;

  /** MIME type (e.g., "image/jpeg", "application/pdf") */
  mimeType: string;

  /** Upload timestamp (epoch milliseconds) */
  uploadedAt: number;

  /** Upload order (for sorting multiple proofs) */
  order: number;

  /** Optional metadata (dimensions for images, duration for videos) */
  metadata?: {
    width?: number;
    height?: number;
    duration?: number;
  };
}

/**
 * Faculty review and remarks
 * Added when faculty reviews submitted activities
 */
export interface ActivityReview {
  /** Faculty member UID who reviewed */
  reviewedBy: string;

  /** Faculty member name (denormalized for display) */
  reviewerName: string;

  /** Faculty's remarks / feedback */
  remarks: string;

  /** Score given (0-100, optional) */
  score?: number;

  /** Review date (epoch milliseconds) */
  reviewedAt: number;

  /** Points awarded if applicable */
  pointsAwarded?: number;
}

/**
 * Comments/notes from student to faculty
 * Used in revision request flow
 */
export interface ActivityComment {
  /** Commenter UID (student or faculty) */
  userId: string;

  /** Commenter name (denormalized) */
  userName: string;

  /** Comment text */
  text: string;

  /** Comment timestamp */
  createdAt: number;

  /** Optional attachment URL */
  attachmentUrl?: string;
}

/**
 * Core Activity document in Firestore
 *
 * Firestore path: `/activities/{activityId}`
 * Subcollections: `/activities/{activityId}/comments`
 */
export interface Activity {
  /** Unique activity ID (auto-generated by Firestore) */
  id: string;

  /** Redundant student identifier used in security rules */
  studentId: string;

  /** Institution tenant ID for isolation/multi-campus support */
  institutionId?: string;

  /** Student who submitted the activity */
  submittedBy: string;

  /** Student name (denormalized for list views) */
  submittedByName: string;

  /** Student's avatar (denormalized) */
  submittedByAvatar?: string;

  /** Activity title / name */
  title: string;

  /** Detailed description of the activity */
  description: string;

  /** Activity category */
  category: ActivityCategory;

  /** Specific activity type */
  type: ActivityType;

  /** Activity date (epoch milliseconds) */
  activityDate: number;

  /** Activity location (optional) */
  location?: string;

  /** Organization/Institution name (for external activities) */
  organization?: string;

  /** Duration in hours */
  durationHours?: number;

  /** Certificates/Awards received (comma-separated) */
  certificatesAwards?: string;

  /** Current status in the lifecycle */
  status: ActivityStatus;

  /** Proof files (screenshots, certificates, documents) */
  proofFiles: ProofFile[];

  /** Faculty review if submitted and reviewed */
  review?: ActivityReview;

  /** Points awarded by faculty */
  pointsAwarded?: number;

  /** Denormalized review timestamp for quick filtering */
  reviewedAt?: number;

  /** Comments thread between student and faculty */
  comments?: ActivityComment[];

  /** Assigned to faculty member UID (for distribution) */
  assignedTo?: string;

  /** Assigned to faculty name (denormalized) */
  assignedToName?: string;

  /** Featured in portfolio or other highlights */
  isFeatured: boolean;

  /** Tags for filtering and search */
  tags: string[];

  /** Collaborators (other students involved) */
  collaborators?: string[];

  /** Document creation timestamp */
  createdAt: number;

  /** Document last update timestamp */
  updatedAt: number;

  /** Submitted for review timestamp (when status changed to SUBMITTED) */
  submittedAt?: number;

  /** Last modified by (uid) */
  lastModifiedBy?: string;

  /** Soft delete flag (for data retention) */
  isDeleted?: boolean;

  /** Soft delete timestamp */
  deletedAt?: number;
}

/**
 * Activity update payload
 * Used by activity edit/update API
 */
export interface ActivityUpdate {
  title?: string;
  description?: string;
  category?: ActivityCategory;
  type?: ActivityType;
  activityDate?: number;
  location?: string;
  organization?: string;
  durationHours?: number;
  certificatesAwards?: string;
  tags?: string[];
  isFeatured?: boolean;
  status?: ActivityStatus;
}

/**
 * Activity creation request
 * Used by form submission / API
 */
export interface ActivityCreateRequest {
  title: string;
  description: string;
  category: ActivityCategory;
  type: ActivityType;
  activityDate: number;
  location?: string;
  organization?: string;
  durationHours?: number;
  certificatesAwards?: string;
  tags?: string[];
  proofFileIds?: string[]; // Cloudinary public_ids
  proofFiles?: ProofFile[];
}

/**
 * Activity filter criteria for queries
 * Supports multiple filter dimensions
 */
export interface ActivityFilterCriteria {
  /** Filter by student UID */
  submittedBy?: string;

  /** Filter by status */
  status?: ActivityStatus | ActivityStatus[];

  /** Filter by category */
  category?: ActivityCategory | ActivityCategory[];

  /** Filter by type */
  type?: ActivityType | ActivityType[];

  /** Filter by date range */
  dateRange?: {
    startDate: number;
    endDate: number;
  };

  /** Filter by assigned faculty */
  assignedTo?: string;

  /** Filter by tags (any match) */
  tags?: string[];

  /** Featured activities only */
  featuredOnly?: boolean;

  /** Search query (title/description) */
  searchQuery?: string;

  /** Department filter (from denormalized student data) */
  department?: string;
}

/**
 * Pagination response for activities
 * Supports cursor-based pagination
 */
export interface ActivityListResponse {
  /** Array of activities */
  activities: Activity[];

  /** Cursor for next page */
  nextCursor?: string;

  /** Cursor for previous page */
  prevCursor?: string;

  /** Total count available */
  totalCount?: number;

  /** Indicates if more results exist */
  hasMore: boolean;
}

/**
 * Activity statistics for dashboard
 * Aggregated data for student/faculty views
 */
export interface ActivityStats {
  /** Total activities submitted by student */
  totalSubmitted: number;

  /** Total approved activities */
  totalApproved: number;

  /** Total under review */
  totalUnderReview: number;

  /** Total rejected */
  totalRejected: number;

  /** Average points awarded */
  averagePoints?: number;

  /** Total points earned */
  totalPoints: number;

  /** Activities by category breakdown */
  byCategory: Record<ActivityCategory, number>;

  /** Most recent activity date */
  lastActivityDate?: number;

  /** Approval rate (approved / total) percentage */
  approvalRate: number;
}
