/**
 * Notification Type Definitions
 *
 * Real-time notifications via Firestore listeners.
 * Covers activity updates, faculty remarks, system announcements.
 *
 * Requirements:
 * - Real-time Firestore listener integration
 * - Toast + badge display in UI
 * - Mark as read / archive functionality
 * - Notification preferences per user
 */

/**
 * Notification types in the system
 * @enum {string}
 */
export enum NotificationType {
  // Activity-related
  ACTIVITY_SUBMITTED = "activity_submitted",
  ACTIVITY_UNDER_REVIEW = "activity_under_review",
  ACTIVITY_APPROVED = "activity_approved",
  ACTIVITY_REJECTED = "activity_rejected",
  ACTIVITY_REVISION_REQUESTED = "activity_revision_requested",
  ACTIVITY_COMMENT_ADDED = "activity_comment_added",

  // System
  ANNOUNCEMENT = "announcement",
  SYSTEM_UPDATE = "system_update",
  DEADLINE_REMINDER = "deadline_reminder",
  MAINTENANCE = "maintenance",

  // User-related
  USER_REGISTERED = "user_registered",
  PROFILE_UPDATED = "profile_updated",
  PASSWORD_CHANGED = "password_changed",
  SESSION_EXPIRED = "session_expired",

  // Faculty-specific
  NEW_SUBMISSION_ASSIGNED = "new_submission_assigned",
  BULK_ASSIGNMENT = "bulk_assignment",

  // Admin-specific
  SUSPICIOUS_ACTIVITY = "suspicious_activity",
  USER_ROLE_CHANGED = "user_role_changed",
}

/**
 * Notification priority levels
 * @enum {string}
 */
export enum NotificationPriority {
  LOW = "low",
  NORMAL = "normal",
  HIGH = "high",
  CRITICAL = "critical",
}

/**
 * Notification action types
 * Defines what action the notification triggers
 */
export interface NotificationAction {
  /** Type of action (LINK, APPROVE, REJECT, etc.) */
  type: "link" | "approve" | "reject" | "archive" | "view";

  /** Target URL or resource ID */
  target?: string;

  /** Display label for the action button */
  label: string;
}

/**
 * Notification recipient preferences
 * Controls which notifications user receives
 */
export interface NotificationPreferences {
  /** User UID */
  userId: string;

  /** Enable email notifications */
  emailNotifications: boolean;

  /** Enable in-app notifications */
  inAppNotifications: boolean;

  /** Enable push notifications (browser) */
  pushNotifications: boolean;

  /** Enable notifications during operating hours only */
  quietHours: {
    enabled: boolean;
    startTime?: string; // "22:00" format
    endTime?: string; // "08:00" format
  };

  /** Notification types to mute */
  mutedNotificationTypes: NotificationType[];

  /** Last preferences update timestamp */
  updatedAt: number;
}

/**
 * Core Notification document in Firestore
 *
 * Firestore path: `/users/{userId}/notifications/{notificationId}`
 * Allows per-user notification isolation for scalability
 */
export interface Notification {
  /** Unique notification ID (auto-generated by Firestore) */
  id: string;

  /** User who receives this notification */
  recipientId: string;

  /** Notification type */
  type: NotificationType;

  /** Priority level */
  priority: NotificationPriority;

  /** Notification title */
  title: string;

  /** Detailed message body */
  message: string;

  /** Dynamic data for message interpolation */
  data?: Record<string, any>;

  /** Link or action associated with notification */
  action?: NotificationAction;

  /** Icon/avatar URL for display */
  icon?: string;

  /** URL of related resource (activity, user, etc.) */
  relatedResourceUrl?: string;

  /** ID of related resource (activity_id, user_id, etc.) */
  relatedResourceId?: string;

  /** Notification read status */
  isRead: boolean;

  /** Timestamp when notification was read */
  readAt?: number;

  /** Notification archived status */
  isArchived: boolean;

  /** Timestamp when notification was archived */
  archivedAt?: number;

  /** Expiration timestamp (for auto-cleanup) */
  expiresAt?: number;

  /** Document creation timestamp */
  createdAt: number;

  /** Last update timestamp */
  updatedAt: number;

  /** Send email to user (flag set at creation) */
  sendEmail?: boolean;

  /** Email sent timestamp */
  emailSentAt?: number;

  /** Email open status (optional email tracking) */
  emailOpened?: boolean;
}

/**
 * Batch notification creation request
 * Used for mass notifications (announcements, deadline reminders)
 */
export interface BatchNotificationRequest {
  /** Notification type */
  type: NotificationType;

  /** Priority level */
  priority: NotificationPriority;

  /** Notification title */
  title: string;

  /** Message template (may use {{variable}} syntax) */
  message: string;

  /** Recipients UIDs (empty = all users, filtered by role) */
  recipientIds?: string[];

  /** Filter by role (if recipientIds not specified) */
  recipientRole?: "student" | "faculty" | "admin";

  /** Filter by department (optional) */
  department?: string;

  /** Dynamic data for template interpolation */
  data?: Record<string, any>;

  /** Action associated with notifications */
  action?: NotificationAction;

  /** Icon URL */
  icon?: string;

  /** Send emails with notifications */
  sendEmails?: boolean;
}

/**
 * Notification statistics for user
 * Used in notification center, bell count, etc.
 */
export interface NotificationStats {
  /** User UID */
  userId: string;

  /** Total unread notifications */
  unreadCount: number;

  /** Total archived notifications */
  archivedCount: number;

  /** Total unread & non-archived */
  activeCount: number;

  /** Count by priority */
  countByPriority: {
    low: number;
    normal: number;
    high: number;
    critical: number;
  };

  /** Count by type (top 5) */
  countByType: Record<string, number>;

  /** Last notification timestamp */
  lastNotificationAt?: number;

  /** Last read notification timestamp */
  lastReadAt?: number;
}

/**
 * Notification query filters
 * For fetching notifications with various criteria
 */
export interface NotificationQueryFilter {
  /** Filter by unread status */
  unreadOnly?: boolean;

  /** Filter by archived status */
  excludeArchived?: boolean;

  /** Filter by type(s) */
  types?: NotificationType[];

  /** Filter by priority */
  priority?: NotificationPriority | NotificationPriority[];

  /** Date range filter */
  dateRange?: {
    startDate: number;
    endDate: number;
  };

  /** Search in title/message */
  searchQuery?: string;

  /** Sort order */
  sortBy?: "newest" | "oldest" | "priority";

  /** Limit results */
  limit?: number;

  /** Offset for pagination */
  offset?: number;
}

/**
 * Notification list response
 * With pagination support
 */
export interface NotificationListResponse {
  /** Array of notifications */
  notifications: Notification[];

  /** Total count of matching notifications */
  totalCount: number;

  /** Total unread count in current query */
  unreadCount: number;

  /** Indicates if more results exist */
  hasMore: boolean;

  /** Next offset for pagination */
  nextOffset?: number;
}

/**
 * Activity-related notification payload
 * Specific data structure for activity notifications
 */
export interface ActivityNotificationPayload {
  /** Related activity ID */
  activityId: string;

  /** Activity title */
  activityTitle: string;

  /** Activity status */
  status: string;

  /** Faculty remarks (for approval/rejection) */
  remarks?: string;

  /** Points awarded */
  points?: number;

  /** Submission timestamp */
  submissionDate?: number;

  /** Faculty name (who reviewed) */
  facultyName?: string;
}

/**
 * Announcement notification payload
 * For system-wide announcements
 */
export interface AnnouncementNotificationPayload {
  /** Announcement title */
  title: string;

  /** Announcement body */
  body: string;

  /** Category (deadline, event, maintenance, etc.) */
  category: string;

  /** Deadline timestamp (if applicable) */
  deadline?: number;

  /** Icon/emoji */
  icon?: string;

  /** Read more link */
  moreLink?: string;
}
